sudo: false
language: node_js
node_js:
- '8'
env:
  matrix:
  - MODE=lint
  - MODE=build
  - MODE=test
matrix:
  fast_finish: true
install:
- npm run ci:install
script:
- scripts/ci/travis-ci-script.sh
