name: Build
on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  build:
    name: Test
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: '13.x'

      - name: Install dependencies
        run: yarn

      - name: Lint typescript
        run: npm run lint

      - name: Build modules
        run: npm run build

      - name: Test modules
        run: npm run test
